name: Publish Documentation

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
      - name: Install Dependencies
        run: pip install sphinx sphinx-rtd-theme myst-parser
      #----------------------------------------------
      # Build documentation
      #----------------------------------------------
      - name: Build documentation
        run: sphinx-build -b html docs/source docs/build

      #----------------------------------------------
      # Clone documentation
      #----------------------------------------------
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: pages
      #----------------------------------------------
      # Move documentation
      #----------------------------------------------
      - name: Move documentation
        run: |
          rm -r pages/docs/*
          mv -f docs/build/* pages/docs/
      #----------------------------------------------
      # Commit & Push changes
      #----------------------------------------------
      - name: Commit and Push
        run: |
          cd pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f docs/
          git commit -m "Updated documentation"
          git push
